name: Build and publish nightly
on:
  push:
    branches:
      - 'master'
jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest
    env:
      PREFIX: "/usr"
      GNU_MIRROR: "https://mirror.checkdomain.de/gnu"
      NEWLIB_MIRROR: "https://ftp.gwdg.de/pub/linux/sources.redhat.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: >
          sudo apt-get install pkg-config gcc g++ flex bison gawk
          gettext bzip2 lzma xz-utils libboost-dev libexpat1-dev
          libgc-dev libgmp-dev zlib1g-dev libipt-dev libmpc-dev
          libmpfr-dev libncurses5-dev libreadline-dev texinfo

      - name: Build
        run: ./.github/scripts/build.sh

  deploy_deb:
    name: "deb: trigger Launchpad rebuild"
    runs-on: ubuntu-latest
    needs: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Launchpad: trigger nightly deb rebuild"
        run: .ci/trigger-launchpad-build.sh --slug="~dciabrin/ngdevkit/+git/ngdevkit-toolchain" --name="Travis%20Deploy"
        env:
          LAUNCHPAD_TOKEN: ${{ secrets.LAUNCHPAD_TOKEN }}
          LAUNCHPAD_TOKEN_SECRET: ${{ secrets.LAUNCHPAD_TOKEN_SECRET }}

  deploy_brew:
    name: "brew: trigger bottle rebuild"
    runs-on: ubuntu-latest
    needs: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Brew: push new nightly revision and bottle"
        run: |
          git config --global user.name 'CI build bot'
          git config --global user.email '<>'
          git config --global url."https://api@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/dciabrin/homebrew-ngdevkit .ci/homebrew-ngdevkit
          .ci/homebrew-ngdevkit/.ci/bump-project-nightly-build.sh ngdevkit-toolchain
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: "Cleanup old nightly tags"
        run: .ci/gc-nightly-tags.sh --user=dciabrin --repo=ngdevkit-toolchain --tag-regex='^refs/tags/nightly-[0-9]*'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
